ROOT     := $(abspath ..)
GTEST    := $(ROOT)/../libs/googletest/googletest

TEST_BIN := $(DIST)/spore_c_test

CXXFLAGS_TEST := $(CXXFLAGS_COMMON) -I$(GTEST)/include

SRCS     := $(wildcard source/*.cpp) \
            $(GTEST)/src/gtest-all.cc \
            $(wildcard test/*.cpp)

FILTER   ?=

.PHONY: test clean-test

test: $(TEST_BIN)
	@$(TEST_BIN) $(if $(FILTER),--gtest_filter=$(FILTER),)

$(TEST_BIN): $(SRCS) $(PARSER_LIBRARY) | $(DIST)
	$(CXX) $(CXXFLAGS_TEST) -I$(GTEST) $(SRCS) $(PARSER_LIBRARY) -o $@ -lpthread

$(PARSER_LIBRARY):
	@echo "Parser library does not exist: $(PARSER_LIBRARY)"
	@echo "Run make check in ../parser first."
	@false

clean-test:
	@rm -f $(TEST_BIN)
