# Toolchain: native Apple Clang on macOS (Apple Silicon)
# Requires: Xcode Command Line Tools (xcode-select --install)

ROOT  := $(abspath ..)
DIST  := $(ROOT)/dist

LIB_STATIC   := libspore_c.a
LIB_STATIC_D := libspore_c_d.a
LIB_SHARED   := libspore_c.dylib
LIB_SHARED_D := libspore_c_d.dylib

SRCS := $(wildcard source/*.cpp)

CXX  := clang++
AR   := ar

CXXFLAGS_COMMON  := -std=c++17 -arch arm64 -fPIC -Iinclude -Isource -I../parser/include
CXXFLAGS_RELEASE := $(CXXFLAGS_COMMON) -O2 -DNDEBUG
CXXFLAGS_DEBUG   := $(CXXFLAGS_COMMON) -g -O0 -DDEBUG

RELEASE_OBJS := $(patsubst source/%.cpp,source/%.o,$(SRCS))
DEBUG_OBJS   := $(patsubst source/%.cpp,source/%_d.o,$(SRCS))

.PHONY: release debug clean

release: $(DIST)/$(LIB_STATIC) $(DIST)/$(LIB_SHARED)
debug:   $(DIST)/$(LIB_STATIC_D) $(DIST)/$(LIB_SHARED_D)

$(DIST)/$(LIB_STATIC): $(RELEASE_OBJS) | $(DIST)
	$(AR) rcs $@ $^

$(DIST)/$(LIB_SHARED): $(RELEASE_OBJS) | $(DIST)
	$(CXX) -arch arm64 -dynamiclib -o $@ $^ $(DIST)/libspore_parser.a

$(DIST)/$(LIB_STATIC_D): $(DEBUG_OBJS) | $(DIST)
	$(AR) rcs $@ $^

$(DIST)/$(LIB_SHARED_D): $(DEBUG_OBJS) | $(DIST)
	$(CXX) -arch arm64 -dynamiclib -o $@ $^ $(DIST)/libspore_parser_d.a

source/%.o: source/%.cpp
	$(CXX) $(CXXFLAGS_RELEASE) -c $< -o $@

source/%_d.o: source/%.cpp
	$(CXX) $(CXXFLAGS_DEBUG) -c $< -o $@

$(DIST):
	@mkdir -p $@

clean:
	@rm -f $(DIST)/$(LIB_STATIC) $(DIST)/$(LIB_STATIC_D) \
	       $(DIST)/$(LIB_SHARED) $(DIST)/$(LIB_SHARED_D) \
	       $(RELEASE_OBJS) $(DEBUG_OBJS)
