ROOT     := $(abspath ..)
GTEST    := $(ROOT)/../libs/googletest/googletest

TEST_BIN := $(DIST)/parser_test

CXXFLAGS_TEST := $(CXXFLAGS_COMMON) -I$(GTEST)/include

SRCS     := $(wildcard source/*.cpp) \
            $(GTEST)/src/gtest-all.cc \
            $(wildcard test/*.cpp)

FILTER   ?=

.PHONY: test clean-test

test: $(TEST_BIN)
	@$(TEST_BIN) $(if $(FILTER),--gtest_filter=$(FILTER),)

$(TEST_BIN): $(SRCS) | $(ROOT)/dist
	$(CXX) $(CXXFLAGS_TEST) -I$(GTEST) $^ -o $@ -lpthread

clean-test:
	@rm -f $(TEST_BIN)
